version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD="qwerty65"
      - MYSQL_USER="root"
      - MYSQL_PASSWORD="qwerty65"
      - MYSQL_DATABASE="db1"
    command: 
      - --default-authentication-plugin=mysql_native_password
    networks:
      - my_network    
  app:
    build:
      context: ./
    ports:
      - "6000:8081"
    networks:
      - my_network 
    depends_on:
      - db
    
networks:
  my_network: