version: '3'
services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "qwerty65"
        MYSQL_USER: "root"
        MYSQL_PASSWORD: "qwerty65"
        MYSQL_DATABASE: "db1"
        container_name: "db1-container"
  web:
    build: .
    ports:
      - "8085:8081"
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - "db:database"
  networks: 
    name: "exp1"